### ISSUE TITLE
jdk.tools:12    这个包怎么回事

### ISSUE THREAD

**Issue by l15047357715** [OysterQAQ/Pixiv-Illustration-Collection-Backend#26]
<dependency>
        <groupId>jdk.tools</groupId>
        <artifactId>jdk.tools</artifactId>
        <version>12</version>
        <scope>system</scope>
        <systemPath>${java.home}/lib/tools.jar</systemPath>
</dependency>

**Comment by l15047357715** [comment]
system omitted for conflict with 12

**Comment by l15047357715** [comment]
jdk12没有这个包

**Comment by OysterQAQ** [comment]
需要从jdk8中提取
