### ISSUE TITLE
接口文档内部分api的请求参数没有加上Headers:Authorization

### ISSUE THREAD

**Issue by willbe03** [OysterQAQ/Pixiv-Illustration-Collection-Backend#28]
比如/illustrations部分
请求参数应为

**Headers**

| 参数名称  | 参数值  |  是否必须 | 示例  | 备注  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| Authorization  |   | 是  |   |   |

**Query**
| ------------ |
| ... |

**Comment by OysterQAQ** [comment]
请默认所有接口都加入Authorization请求头
