### ISSUE TITLE
搜索图片的xRestrict参数该如何设置呢？

### ISSUE THREAD

**Issue by Pzzzzz5142** [OysterQAQ/Pixiv-Illustration-Collection-Backend#29]
设置为0有结果，但是非0数就没有返回的结果。

（另外问一下有没有做minSanityLevel参数的打算呢（（（

**Comment by OysterQAQ** [comment]
xRestrict只能为0，这个参数为1的话都是一些高危图片，minSanityLevel的话估计不会做 限制在了6的级别，这个级别已经可能存在漏点等情况了
