### ISSUE TITLE
随机接口API

### ISSUE THREAD

**Issue by receyuki** [OysterQAQ/Pixiv-Illustration-Collection-Backend#30]
想问一下还会提供以前那样的随机图片API吗？
或者只是我没找到文档？

**Comment by OysterQAQ** [comment]
目前的随机接口是不可用的，后续可能会有，后续将从特殊筛选比例的画作中进行随机

**Comment by receyuki** [comment]
> 目前的随机接口是不可用的，后续将从特殊筛选比例的画作中进行随机，请关注

感谢回复

**Comment by OysterQAQ** [comment]
请不要关闭issue 当功能上线后会在这里回复

**Comment by OysterQAQ** [comment]
### 随机二次元图片api

#### 说明

```
https://open.pixivic.net/wallpaper/{platform}/random?size=large&domain=https://i.pixiv.cat&webp=0&detail=1
```

| 参数位置 | 参数名   | 说明                                                         |
| -------- | -------- | ------------------------------------------------------------ |
| url路径  | platform | 可选（pc｜mobile），pc指的是16:9，mobile指的是9:16，pc指标下2.2w张图片，mobile指标下14.4w张图片 |
| url参数  | size     | 可选（original｜large｜medium｜squareMedium），图片大小      |
| url参数  | domain   | 反向代理域名前缀，默认值是https://i.pixiv.cat                |
| url参数  | webp     | 是否webp图片url，仅在size=large时候有效                      |
| url参数  | detail   | 是否在重定向url中返回详细信息                                |

#### 示例

```
https://open.pixivic.net/wallpaper/pc/random?size=large&domain=https://i.pixiv.cat&webp=0&detail=1
```

![](https://open.pixivic.net/wallpaper/pc/random?size=large&domain=https://i.pixiv.cat&webp=0&detail=1)

#### 稳定性

一年以上

#### 限制

单个ip每10分钟内限制调用600次

**Comment by OysterQAQ** [comment]
部分图片存在 404 情况（极少）

**Comment by fengx1a0** [comment]
就这么close了？你的图片数据库是随机爬取的吗，随机出来的图片貌似质量不稳定，而且综合我的测试来看低质量的图片偏多，建议直接爬榜，期待推主早日能够完善。

**Comment by OysterQAQ** [comment]
> 就这么close了？你的图片数据库是随机爬取的吗，随机出来的图片貌似质量不稳定，而且综合我的测试来看低质量的图片偏多，建议直接爬榜，期待推主早日能够完善。

收藏数只限制了200以上 日榜符合要求的图片到不了这么多 这个api是开放的 所以可能不会花太多时间更新

**Comment by fengx1a0** [comment]
谢谢
